---
title: "CV"
editor: visual
---

|               |                                  |                   |                  |
|:-------------:|:--------------------------------:|:-----------------:|:----------------:|
| Ph.D. Student | Florida International University | jstur015\@fiu.edu | \(703\) 509-9960 |

### Education

|                                                                  |              |
|------------------------------------------------------------------|-------------:|
| Florida International University - Ph.D., Earth Systems Science  | 2022-Present |
| California State Polytechnic University, Pomona - M.S., Biology  |         2022 |
| University of Southern California -  B.S., Environmental Studies |         2018 |

### Employment

|                                                                                                                |                     |
|----------------------------------------------------------------------------------------------------------------|--------------------:|
| **Graduate Research Assistant** - Florida International University, *Miami, FL* (Advisor: Dr. Jennifer Rehage) |        2022-Present |
| **Graduate Teaching Assistant** - Cal Poly Pomona, *Pomona, CA* (Advisor: Dr. Jeremy Claisse)                  |           2019-2021 |
| **Lab Technician** - USC Cnidarian Evolutionary Ecology Lab, *Los Angeles, CA* (PI: Dr. Carly Kenkel)          | Aug. 2017-Jan. 2019 |
| **Undergraduate Research Assistant –** USC Wrigley Marine Science Center, *Santa Catalina Island, CA*          |                2017 |
| **Undergraduate Research Assistant –** Steve Kay Laboratory USC *Keck School of Medicine, Los Angeles, CA*     |                2015 |
| **Undergraduate Research Assistant –** The Edmands Lab: Population & Conservation Genetics *, Los Angeles CA*  |                2014 |

### Publications

|                                                                                                                                                                                                                                                           |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **Sturges JW**, WR James, R Rezek, RO Santos, M White, G Badlowski, S Trabelsi, JA Massie, J Nelson, J Trexler, and JS Rehage (**in review**). Seasonality drives green and brown energy pathways in food webs across an ecosystem gradient. *Ecosphere*. |
| **Sturges JW** & Claisse JT (in review). Quarry rock reef design features influence fish assemblage structure across a systematically heterogenous restoration reef. *Marine Ecological Research*.                                                        |

### Funding

|                                                                                                                             |      |
|-----------------------------------------------------------------------------------------------------------------------------|-----:|
| Supplemental Research Grant; Funded by NSF CREST Center for Aquatic Chemistry & Env. **(\$1,000**)                          | 2023 |
| Institute of Environment Travel Grant; (**\$500**)                                                                          | 2023 |
| Graduate Student Research Aware – California State University Council on Ocean Affairs, Science, & Technology **(\$5,000**) | 2022 |
| Student Travel Grant; Funded by US-LTER **(\$1,000**)                                                                       | 2022 |
| FIU ForEverglades Scholarship – Principal Investigator; Funded by Everglades Foundation **(\$25,000**)                      | 2022 |
| Student Travel Grant; Funded by Florida Chapter of American Fisheries Society (**\$300**)                                   | 2022 |
| Colin Cone Writing Scholarship; Funded by Florida Outdoor Writers Association **(\$1,000**)                                 | 2021 |

#### ***Proposals pending or not selected for funding***

|                                                                                     |      |
|-------------------------------------------------------------------------------------|-----:|
| Florida Forage Fish Research Fellowship; FFFC & FWRI **(\$15,000**)                 | 2024 |
| Ford Foundation Predoctoral Fellowship; Ford Foundation **(\$30,000**)              | 2022 |
| Conservation Research Grant; North American Native Fishes Association (**\$1,000**) | 2020 |

### Awards & Honors

|                                                                                         |      |
|-----------------------------------------------------------------------------------------|-----:|
|                                                                                         |      |
| Student of the Year, *Florida Coastal Everglades LTER*                                  | 2023 |
| Best Student Poster Award***,** Florida Coastal Everglades LTER All-Scientists Meeting* | 2023 |
| Best Student Oral Presentation Award, *Southeastern Fishes Council Meeting*             | 2021 |
| Best Student Poster Presentation Award, *Southeastern Fishes Council Meeting*           | 2019 |

### Teaching & Mentor Experience

#### ***Teaching***

|                                                                                                 |           |
|-------------------------------------------------------------------------------------------------|----------:|
| **Principles of Ecology Lab (BIOL 3130):** 3 Semesters **-** Tennessee Technological University | 2020-2021 |
| **Principles of Biology Lab (BIOL 1113):** 2 Semesters - Tennessee Technological University     |      2019 |

#### ***Mentoring***

|                                                                                                                                                                                                                                                                |              |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------:|
| **Graduate & Undergraduate Student Research Mentor**: MS students - Florida International University (5); UG Students - Florida International University (12), Tennessee Technological University (4); NSF-REU Students – Florida International University (2) | 2019-Present |

### University & Professional Service

|                                                                                                            |              |
|------------------------------------------------------------------------------------------------------------|-------------:|
| Aquatic Technical Working Group Committee, *National Ecological Observatory Network*                       | 2023-Present |
| Broadening Inclusion Committee, *Florida Coastal Everglades LTER*                                          | 2022-Present |
| Diversity, Equity, and Inclusion Committee, *Southeastern Fishes Council*                                  | 2021-Present |
| Florida AFS - Reefs to Rivers Blog, Editor, *Florida Chapter of the American Fisheries Society*            |    2022-2023 |
| Florida AFS Student Subunit, University Liaison, *Florida Chapter of the American Fisheries Society*       |    2022-2023 |
| FCE-LTER Student Subunit, Secretary, *Florida Coastal Everglades LTER*                                     |    2021-2022 |
| Biology Graduate Student Society, President, *Biology Department of Tennessee Technological University*    |    2020-2021 |
| City of Cookeville Fishing Derby, Event Coordinator, *Tennessee Chapter of the American Fisheries Society* |         2020 |
| Biology Graduate Student Society, Treasurer, *Biology Department of Tennessee Technological University*    |         2019 |
| Life Below the Water Line Community Outreach Program, *Ohio River Valley Water Sanitation Commission*      |         2018 |

### Selected Presentations

|                                                                                                                                                                                           |      |
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----:|
| Species richness and functional diversity drives nutrient supply stability across marine ecosystems; *Florida Coastal Everglades LTER All-Scientist meeting – poster presentation*        | 2024 |
| Species richness and functional diversity drives nutrient supply stability across marine ecosystems; *Florida American Fisheries Society annual meeting – poster presentation*            | 2024 |
| Consumer nutrient dynamics in coastal ecosystem in the wake of global change; *Florida American Fisheries Society annual meeting – poster presentation*                                   | 2023 |
|                                                                                                                                                                                           |      |
| Consumer nutrient dynamics in coastal ecosystem in the wake of global change; *NSF CREST Center for Aquatic Chemistry & Env. All-Scientists Meeting – poster presentation*                | 2023 |
| When world’s collide: Consumer nutrient dynamics in the coastal Everglades; *Florida Coastal Everglades LTER All-Scientists meeting – poster presentation*                                | 2023 |
| When world’s collide: Multi-directional movements of fishes and their ecological importance; *Florida American Fisheries Society annual meeting – poster presentation*                    | 2022 |
| South Florida coastal fisheries acoustic telemetry project update; *Florida Atlantic Coast Telemetry Meeting – oral presentation*                                                         | 2021 |
| Consumer functional roles and the biodiversity of freshwater fishes in the southeast; *Florida International University Department of Earth & Science Seminar Series – oral presentation* | 2021 |
| Salmon of the South: Suckers in Citico Creek; *Southeastern Fishes Council annual meeting – oral presentation*                                                                            | 2021 |
| Salmon of the South: Nutrient contributions of an adfluvial catostomid; *Tennessee Technological University Seminar Series – oral presentation*                                           | 2021 |
| Growth of Rainbow Trout (*Oncorhynchus mykiss*) in Two Tennessee Tailwaters; *Tennessee Chapter of the American Fisheries Society annual meeting – oral presentation (second author)*     | 2021 |
| Suckers - salmon of the South? *Tennessee Rare Fishes Meeting – oral presentation*                                                                                                        | 2020 |
| Abundance estimates of spawning catostomids in a small, oligotrophic stream using aerial imagery; *Southeastern Fishes Council annual meeting – oral presentation*                        | 2019 |
| Native brook trout conservation genetics; *Tennessee Technological University Department of Biology Seminar Series – oral presentation*                                                   | 2019 |

### Specialized Skills

|                                                  |
|--------------------------------------------------|
| Proficiency in R, Git, & GitHub                  |
| Experience in JavaScript, Python, HTML, & ArcGIS |

| Certified for AAUS scientific diving, PADI advanced open water & rescue \|
| Field experience with electrofishing, seining, and free diving
| 
| Extensive acoustic, passive integrated transponder, and coded wired tagging experience \|
| Extensive boating and trailering experience in marine and freshwater systems \|
| Extensive fish identification, water quality analysis (discrete auto-analyzer and handheld fluorometry), macroinvertebrate identification \|
| Experience in DNA extractions \|
